services:
  - type: web
    name: thinkboard-app
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/notes
    envVars:
      - key: MONGODB_URL
        sync: false
