services:
  - type: web
    name: thinkboard-app
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/notes
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: FRONTEND_URL
        value: https://thinkboard-app.onrender.com
      - key: VITE_API_URL
        value: https://thinkboard-app.onrender.com
